// Code generated by github.com/kybin/bakego. DO NOT EDIT.
package main

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"os"
	"path/filepath"
)

type BakeGoFile struct {
	fname string
	enc string
	data []byte
}

type BakeGo []BakeGoFile

// Extract extracts all remebered files.
func (b BakeGo) Extract() error {
	for _, s := range b {
		fname := s.fname
		enc := s.enc
		data := s.data
		err := os.MkdirAll(filepath.Dir(fname), 0755)
		if err != nil {
			return err
		}
		f, err := os.Create(fname)
		if err != nil {
			return err
		}
		w := bufio.NewWriter(f)
		decoded := data
		if enc == "hex" {
			d, err := fromHex(data)
			if err != nil {
				return err
			}
			decoded = d
		}
		_, err = w.Write(decoded)
		if err != nil {
			return err
		}
		w.Flush()
	}
	return nil
}

// Ensure checks all the BakeGo files are exist.
// It will return nil if all files are exist or return error.
//
// It does not check the files are modified or not.
func (b BakeGo) Ensure() error {
	for _, s := range b {
		_, err := os.Stat(s.fname)
		if err != nil {
			return err
		}
	}
	return nil
}

// fromHex are twin functions that lives both inside and outside of generated file.
// Outside one is for testing purpose.
//
// Note: if you change this function, change it's twin function too.
func fromHex(data []byte) ([]byte, error) {
	reverted := make([]byte, 0, len(data))
	lines := bytes.Split(data, []byte("\n"))
	for _, src := range lines {
		dst := make([]byte, hex.DecodedLen(len(src)))
		_, err := hex.Decode(dst, src)
		if err != nil {
			return nil, err
		}
		reverted = append(reverted, dst...)
	}
	return reverted, nil
}

var bakego BakeGo = make([]BakeGoFile, 0)

func init() {
	bakego = append(bakego, BakeGoFile{"tmpl/edit.html", "", []byte(`<!DOCTYPE html>
<html>
<head>
    {{template "style"}}
</head>

<body class="align-center">
    {{template "header" .}}

    <div id="main" class="just-center">
        <div class="width-limit">
			<form action="/save/{{.Title}}" method="POST">
				<div><textarea name="body" rows="20" cols="80" style="width:100%; resize:vertical">{{printf "%s" .Body}}</textarea></div>
				<div><input type="submit" value="Save"></div>
			</form>
    	</div>
    </div>

    {{template "footer"}}
</body>
</html>


`)})
	bakego = append(bakego, BakeGoFile{"tmpl/footer.html", "", []byte(`{{define "footer"}}
    <div id="footer" class="just-center">
        <p>Sample Footer</p>
    </div>
{{end}}

`)})
	bakego = append(bakego, BakeGoFile{"tmpl/header.html", "", []byte(`{{define "header"}}
    <div id="header" class="just-center">
        <div class="width-limit" style="display:flex; align-items:flex-end">
            <div id="title" class="inline"><b>{{.Title}}</b></div>
            <div class="inline" style="width:20px"></div>
            <div class="inline"><a href="/view/{{.Title}}"><span class="header-button">view</span></a></div>
            <div class="inline"><a href="/edit/{{.Title}}"><span class="header-button">edit</span></a></div>
            <div class="inline"><a href="/history/{{.Title}}"><span class="header-button">history</span></a></div>
            <div class="inline" style="flex-grow:1"></div>
            <div class="inline"><a href="?login=1"><span class="header-button">login</span></a></div>
        </div>
    </div>
{{end}}
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/history.html", "", []byte(`<!DOCTYPE html>
<html>
<head>
    {{template "style"}}
</head>

<body class="align-center">
    {{template "header" .}}

    <div id="main" class="just-center">
        <div class="width-limit">
        	{{range .Revs}}
        		<p><a href="/view/{{$.Title}}?rev={{.Num}}">Rev: {{.Num}}, Created: {{.Created}}, Author: {{.Author}}</a></p>
        		<hr>
        	{{end}}
    	</div>
    </div>

    {{template "footer"}}
</body>
</html>

`)})
	bakego = append(bakego, BakeGoFile{"tmpl/login.html", "", []byte(`<!DOCTYPE html>
<html>
<head>
    {{template "style"}}
</head>

<body class="align-center">
    {{template "header" .}}

    <div id="main" class="just-center">
        <div class="width-limit">
			<div style="display:flex; flex-direction:column; align-items:center">
				<div style="color: #cccccc"><h2>Welcome to Whisky.</h2></div>
				<div style="height:40px"></div>
				<div style="display:flex"><input class="login-input" placeholder="username" style="width:240px; padding:4px; font-size:15px"></input></div>
				<div style="height:4px"></div>
				<div style="display:flex"><input type="password" class="login-input" placeholder="password" style="width:240px; padding:4px; font-size:15px"></input></div>
				<div style="height:4px"></div>
				<input type="button" class="login-button" value="Log In" style="width:250px; padding:6px; font-size:15px"/>
				<div style="height:30px"></div> <!-- place holder -->
				<div style="height:4px"></div>
				<div style="height:80px"></div>
				<div style="color: #dddddd">or &nbsp;&nbsp;<a href="?signup=1" style="color:#aa4444"><b>Sign up</b></a>&nbsp;&nbsp;&nbsp;&nbsp;</div>
			</div>
        </div>
    </div>

    {{template "footer"}}
</body>
</html>

`)})
	bakego = append(bakego, BakeGoFile{"tmpl/signup.html", "", []byte(`<!DOCTYPE html>
<html>
<head>
    {{template "style"}}
</head>

<body class="align-center">
    {{template "header" .}}

    <div id="main" class="just-center">
        <div class="width-limit">
			<div style="display:flex; flex-direction:column; align-items:center">
				<div style="color: #cccccc"><h2>Welcome to Whisky.</h2></div>
				<div style="height:40px"></div>
				<div style="display:flex"><input class="signup-input" placeholder="username" style="width:240px; padding:4px; font-size:15px"></input></div>
				<div style="height:4px"></div>
				<div style="display:flex"><input type="password" class="signup-input" placeholder="password" style="width:240px; padding:4px; font-size:15px"></input></div>
				<div style="height:4px"></div>
				<div style="display:flex"><input type="password" class="signup-input" placeholder="re-enter password" style="width:240px; padding:4px; font-size:15px"></input></div>
				<div style="height:4px"></div>
				<input type="button" class="signup-button" value="Sign Up" style="width:250px; padding:6px; font-size:15px"/>
				<div style="height:80px"></div>
				<div style="color: #dddddd">or &nbsp;&nbsp;<a href="?login=1" style="color:#44aa44"><b>Log In</b></a>&nbsp;&nbsp;&nbsp;&nbsp;</div>
			</div>
        </div>
    </div>

    {{template "footer"}}
</body>
</html>

`)})
	bakego = append(bakego, BakeGoFile{"tmpl/style.html", "", []byte(`{{define "style"}}
    <style>
    body {
        margin: 0px;
        padding: 0px;
    }
    table {
        border-collapse: collapse;
    }
    table, th, td {
        border: 1px solid gray;
        padding: 5px 10px;
    }
    pre {
        background-color: #fdfdfd;
        padding: 5px;
        border-style: solid;
        border-radius: 2px;
        border-width: 1px;
        border-color: #dddddd;
    }
    hr {
        border: 0;
        border-top: 1px solid #dddddd;
    }
    a {
        text-decoration: none;
    }
    #header {
        width: 100%;
        background-color: #fdfdfd;
        border-style: solid;
        border-width: 0px 0px 1px 0px;
        border-color: #eeeeee;
        padding: 0px 0px 2px 0px;
    }
    #main {
        width: 100%;
        background-color: #ffffff;
        min-height: 1000px;
        padding: 50px 0px 0px 0px;
    }
    #footer {
        width: 100%;
        background-color: #fdfdfd;
        border-style: solid;
        border-width: 1px 0px 0px 0px;
        border-color: #eeeeee;
    }
    #title {
        font-size: 40px;
    }
    .align-center {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .just-center {
        display: flex;
        justify-content: center;
    }
    .width-limit {
        width: 800px;
    }
    .inline {
        display: inline-block;
    }
    .header-button{
        display: inline-block;
        padding: 10px;
        margin: 0px 10px 0px 0px;
        color: #aaaaaa;
    }
    .login-input {
        border-style: solid;
        border-width: 1px;
        border-radius: 2px;
        border-color: #aaddaa;
        background-color: #fdfdfd;
        box-shadow: inset 0 1px 2px rgba(27,31,35,0.075);
    }
    .login-input::placeholder {
        color: #bbbbbb;
    }
    .login-button {
        border-style: none;
        border-width: 1px;
        border-radius: 2px;
        background-color: #44aa44;
        color: #ffffff;
    }
    .signup-input {
        border-style: solid;
        border-width: 1px;
        border-radius: 2px;
        border-color: #ddaaaa;
        background-color: #fdfdfd;
        box-shadow: inset 0 1px 2px rgba(27,31,35,0.075);
    }
    .signup-input::placeholder {
        color: #bbbbbb;
    }
    .signup-button {
        border-style: none;
        border-width: 1px;
        border-radius: 2px;
        background-color: #aa4444;
        color: #ffffff;
    }
    </style>
{{end}}
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/view.html", "", []byte(`<!DOCTYPE html>
<html>
<head>
    {{template "style"}}
</head>

<body class="align-center">
    {{template "header" .}}

    <div id="main" class="just-center">
        <div class="width-limit">
        {{.HTML}}
        </div>
    </div>

    {{template "footer"}}
</body>
</html>
`)})
}
